### ISSUE TITLE
Feature request: automatic `load` on start.

### ISSUE THREAD

**Issue by sirocyl** [meithecatte/miniforth#7]
Another tricky one, but the premise is simple - `load` and execute one Forth block without any user intervention on boot.

There's quite a bit that could be done with this, including making the environment feel more like an operating system proper.

If the sector it loads is empty, it does nothing, and you're back to the interpreter, as usual.
If this behavior is not desirable, the code could possibly be commented out/removed prior to build.

I noticed that `80` (the current disk number) is on the stack when the interpreter is presented - meaning a `load` command with no arguments will do `80 load`.
So, I use this in a bit of a hack, where I renamed the bootsector `load` word to `forth`; at block 80, is only `80 1 forth`; and in block 1, I had changed the `load` word copy, so that it copies `forth` over to `load`.
Now, you only type `forth` to start the rest of the system. :)

**Comment by meithecatte** [comment]
Whoops, I seem to recall writing a comment explaining why I didn't do it like this in the first place, but it seems to have been lost along the way.

As the commit helpfully linked by GitHub explains, I tend to keep a fallback copy of my code at blocks `101` and up, so having to load everything explicitly also works as a safemode option when I screw up.

Anyway, this is definitely a valid thing to want for other usecases, so I implemented this behind an ifdef - pass `-DAUTOLOAD` to `yasm` and have fun ;3
